import type {
  ExtractedScope,
  NormalizedScope,
} from "@/lib/scope-schema";

export type ScopeDiffStatus =
  | "UNCHANGED"
  | "MODIFIED"
  | "ADDED"
  | "MISSING"
  | "CONFLICT";

export type ScopeDiffMatchMethod =
  | "exact-key"
  | "fuzzy"
  | "none";

export type ScopeDiffConflictType =
  | "REMOVED_ITEM_REAPPEARED";

export type ScopeDiffSection =
  | "deliverables"
  | "features"
  | "exclusions"
  | "clientResponsibilities"
  | "revisionLimits"
  | "assumptions";

type BaseStandardItem =
  | NormalizedScope["deliverables"][number]
  | NormalizedScope["features"][number]
  | NormalizedScope["exclusions"][number]
  | NormalizedScope["clientResponsibilities"][number];

type CandidateStandardItem =
  | ExtractedScope["deliverables"][number]
  | ExtractedScope["features"][number]
  | ExtractedScope["exclusions"][number]
  | ExtractedScope["clientResponsibilities"][number];

type BaseRevisionLimit =
  NormalizedScope["revisionLimits"][number];

type CandidateRevisionLimit =
  ExtractedScope["revisionLimits"][number];

type BaseAssumption =
  NormalizedScope["assumptions"][number];

type CandidateAssumption =
  ExtractedScope["assumptions"][number];

export type ScopeDiffEntry<
  BaseItem,
  CandidateItem,
> = {
  status: ScopeDiffStatus;

  /**
   * The existing persisted item.
   * Null for a newly added candidate item.
   */
  baseItem: BaseItem | null;

  /**
   * The newly extracted candidate item.
   * Null when an existing active item is missing.
   */
  candidateItem: CandidateItem | null;

  /**
   * Stable application-owned identity from the approved scope.
   * Never generated by Gemini.
   */
  baseItemId: string | null;

  /**
   * Position of the candidate item inside the extracted section.
   * Useful later when the reconciliation UI submits decisions.
   */
  candidateIndex: number | null;

  /**
   * How the engine established the match.
   */
  matchMethod: ScopeDiffMatchMethod;

  /**
   * Deterministic similarity score used only for matching.
   */
  matchScore: number | null;

  /**
   * A missing manually-added item cannot simply disappear with the
   * new SOW. The later reconciliation step must ask whether to carry it over.
   */
  requiresCarryOverDecision: boolean;

  conflictType: ScopeDiffConflictType | null;
};

export type TimelineDiff = {
  status:
    | "UNCHANGED"
    | "MODIFIED"
    | "ADDED"
    | "MISSING";

  baseTimeline: NormalizedScope["timeline"];
  candidateTimeline: ExtractedScope["timeline"];

  changedFields: Array<
    "duration"
    | "startCondition"
    | "dependencies"
  >;
};

export type ScopeDiff = {
  deliverables: Array<
    ScopeDiffEntry<
      NormalizedScope["deliverables"][number],
      ExtractedScope["deliverables"][number]
    >
  >;

  features: Array<
    ScopeDiffEntry<
      NormalizedScope["features"][number],
      ExtractedScope["features"][number]
    >
  >;

  exclusions: Array<
    ScopeDiffEntry<
      NormalizedScope["exclusions"][number],
      ExtractedScope["exclusions"][number]
    >
  >;

  clientResponsibilities: Array<
    ScopeDiffEntry<
      NormalizedScope["clientResponsibilities"][number],
      ExtractedScope["clientResponsibilities"][number]
    >
  >;

  revisionLimits: Array<
    ScopeDiffEntry<
      NormalizedScope["revisionLimits"][number],
      ExtractedScope["revisionLimits"][number]
    >
  >;

  assumptions: Array<
    ScopeDiffEntry<
      NormalizedScope["assumptions"][number],
      ExtractedScope["assumptions"][number]
    >
  >;

  timeline: TimelineDiff;
};

/**
 * Normalize text only for comparison.
 *
 * This does NOT modify stored scope or source evidence.
 * Evidence remains governed by the strict source-reference validator.
 */
function normalizeComparableText(
  value: string | undefined,
): string {
  return (value ?? "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");
}

/**
 * Convert a piece of text into a set of semantic-ish tokens.
 *
 * This is intentionally simple and deterministic.
 * We do not use an LLM to decide item identity.
 */
function tokenSet(
  value: string | undefined,
): Set<string> {
  const normalized =
    normalizeComparableText(value);

  const cleaned = normalized.replace(
    /[^\p{L}\p{N}]+/gu,
    " ",
  );

  return new Set(
    cleaned
      .split(" ")
      .filter(Boolean),
  );
}

/**
 * Jaccard similarity gives a deterministic token-overlap score.
 */
function tokenSimilarity(
  left: string | undefined,
  right: string | undefined,
): number {
  const leftTokens = tokenSet(left);
  const rightTokens = tokenSet(right);

  if (
    leftTokens.size === 0 ||
    rightTokens.size === 0
  ) {
    return 0;
  }

  let intersection = 0;

  for (const token of leftTokens) {
    if (rightTokens.has(token)) {
      intersection += 1;
    }
  }

  const union =
    leftTokens.size +
    rightTokens.size -
    intersection;

  return union === 0
    ? 0
    : intersection / union;
}

/**
 * Standard items primarily identify by title.
 *
 * Description is deliberately low weight because descriptions commonly
 * change while the logical item remains the same.
 */
function standardSimilarity(
  base: BaseStandardItem,
  candidate: CandidateStandardItem,
): number {
  const titleA =
    normalizeComparableText(base.title);

  const titleB =
    normalizeComparableText(candidate.title);

  if (titleA && titleA === titleB) {
    return 1;
  }

  const titleTokensA = tokenSet(titleA);
  const titleTokensB = tokenSet(titleB);

  const titleScore = tokenSimilarity(
    titleA,
    titleB,
  );

  // Treat a short title extension such as:
  // "Contact page" -> "Contact Us page"
  // as a strong identity signal.
  //
  // This only applies when every token from the shorter title
  // exists in the longer title, which is safer than simply
  // lowering the global fuzzy threshold.
  const smallerTokens =
    titleTokensA.size <=
    titleTokensB.size
      ? titleTokensA
      : titleTokensB;

  const largerTokens =
    titleTokensA.size <=
    titleTokensB.size
      ? titleTokensB
      : titleTokensA;

  const titleSubsetMatch =
    smallerTokens.size > 0 &&
    [...smallerTokens].every(
      (token) => largerTokens.has(token),
    );

  const titleIdentityScore =
    titleSubsetMatch
      ? 0.9
      : titleScore;

  const descriptionScore =
    tokenSimilarity(
      base.description,
      candidate.description,
    );

  if (
    !base.description &&
    !candidate.description
  ) {
    return titleIdentityScore;
  }

  return (
    titleIdentityScore * 0.85 +
    descriptionScore * 0.15
  );
}

function revisionLimitSimilarity(
  base: BaseRevisionLimit,
  candidate: CandidateRevisionLimit,
): number {
  const baseType =
    normalizeComparableText(base.type);

  const candidateType =
    normalizeComparableText(candidate.type);

  if (
    baseType &&
    baseType === candidateType
  ) {
    return 1;
  }

  const typeScore = tokenSimilarity(
    baseType,
    candidateType,
  );

  const limitScore = tokenSimilarity(
    base.limit,
    candidate.limit,
  );

  return (
    typeScore * 0.85 +
    limitScore * 0.15
  );
}

function assumptionSimilarity(
  base: BaseAssumption,
  candidate: CandidateAssumption,
): number {
  const baseStatement =
    normalizeComparableText(
      base.statement,
    );

  const candidateStatement =
    normalizeComparableText(
      candidate.statement,
    );

  if (
    baseStatement &&
    baseStatement === candidateStatement
  ) {
    return 1;
  }

  return tokenSimilarity(
    baseStatement,
    candidateStatement,
  );
}

/**
 * Semantic equality deliberately ignores:
 *
 * - IDs
 * - provenance
 * - source references
 * - amendment metadata
 * - removal metadata
 * - candidate extraction metadata
 *
 * Those belong to versioning/reconciliation, not semantic content.
 */
function sameStandardMeaning(
  base: BaseStandardItem,
  candidate: CandidateStandardItem,
): boolean {
  return (
    normalizeComparableText(
      base.title,
    ) ===
      normalizeComparableText(
        candidate.title,
      ) &&
    normalizeComparableText(
      base.description,
    ) ===
      normalizeComparableText(
        candidate.description,
      )
  );
}

function sameRevisionLimitMeaning(
  base: BaseRevisionLimit,
  candidate: CandidateRevisionLimit,
): boolean {
  return (
    normalizeComparableText(
      base.type,
    ) ===
      normalizeComparableText(
        candidate.type,
      ) &&
    normalizeComparableText(
      base.limit,
    ) ===
      normalizeComparableText(
        candidate.limit,
      )
  );
}

function sameAssumptionMeaning(
  base: BaseAssumption,
  candidate: CandidateAssumption,
): boolean {
  return (
    normalizeComparableText(
      base.statement,
    ) ===
      normalizeComparableText(
        candidate.statement,
      )
  );
}

/**
 * Matching is intentionally conservative.
 *
 * We first use an exact logical key. If that cannot identify the item
 * uniquely, we allow a strong fuzzy token match.
 *
 * Ambiguous candidates are left unmatched rather than silently guessing.
 */
function matchItems<
  BaseItem extends { id: string; status: string },
  CandidateItem,
>(data: {
  baseItems: BaseItem[];
  candidateItems: CandidateItem[];
  getIdentity: (
    item: BaseItem | CandidateItem,
  ) => string;
  getSimilarity: (
    base: BaseItem,
    candidate: CandidateItem,
  ) => number;
}) {
  const {
    baseItems,
    candidateItems,
    getIdentity,
    getSimilarity,
  } = data;

  const matchedBaseIndexes =
    new Map<number, number>();

  const matchedCandidateIndexes =
    new Map<number, number>();

  // ---------------------------------------------------------------------------
  // Pass 1: unique exact identity keys.
  // ---------------------------------------------------------------------------

  for (
    let candidateIndex = 0;
    candidateIndex < candidateItems.length;
    candidateIndex += 1
  ) {
    const candidate =
      candidateItems[candidateIndex];

    const candidateKey =
      getIdentity(candidate);

    if (!candidateKey) {
      continue;
    }

    const matches: number[] = [];

    for (
      let baseIndex = 0;
      baseIndex < baseItems.length;
      baseIndex += 1
    ) {
      if (
        matchedBaseIndexes.has(
          baseIndex,
        )
      ) {
        continue;
      }

      if (
        getIdentity(
          baseItems[baseIndex],
        ) === candidateKey
      ) {
        matches.push(baseIndex);
      }
    }

    if (matches.length !== 1) {
      continue;
    }

    const baseIndex = matches[0];

    matchedCandidateIndexes.set(
      candidateIndex,
      baseIndex,
    );

    matchedBaseIndexes.set(
      baseIndex,
      candidateIndex,
    );
  }

  // ---------------------------------------------------------------------------
  // Pass 2: conservative fuzzy matching.
  // ---------------------------------------------------------------------------

  const FUZZY_THRESHOLD = 0.72;
  const AMBIGUITY_GAP = 0.1;

  for (
    let candidateIndex = 0;
    candidateIndex < candidateItems.length;
    candidateIndex += 1
  ) {
    if (
      matchedCandidateIndexes.has(
        candidateIndex,
      )
    ) {
      continue;
    }

    const candidate =
      candidateItems[candidateIndex];

    const ranked: Array<{
      baseIndex: number;
      score: number;
      active: boolean;
    }> = [];

    for (
      let baseIndex = 0;
      baseIndex < baseItems.length;
      baseIndex += 1
    ) {
      if (
        matchedBaseIndexes.has(
          baseIndex,
        )
      ) {
        continue;
      }

      const base = baseItems[baseIndex];

      ranked.push({
        baseIndex,
        score: getSimilarity(
          base,
          candidate,
        ),
        active:
          base.status === "active",
      });
    }

    ranked.sort(
      (left, right) => {
        if (
          right.score !== left.score
        ) {
          return right.score - left.score;
        }

        // Prefer an active item over a removed tombstone
        // when similarity is identical.
        if (
          right.active !== left.active
        ) {
          return Number(
            right.active,
          ) - Number(left.active);
        }

        // Stable deterministic tie-breaker.
        return (
          left.baseIndex -
          right.baseIndex
        );
      },
    );

    const best = ranked[0];
    const second = ranked[1];

    if (
      !best ||
      best.score < FUZZY_THRESHOLD
    ) {
      continue;
    }

    if (
      second &&
      best.score -
        second.score <
        AMBIGUITY_GAP
    ) {
      continue;
    }

    matchedCandidateIndexes.set(
      candidateIndex,
      best.baseIndex,
    );

    matchedBaseIndexes.set(
      best.baseIndex,
      candidateIndex,
    );
  }

  return {
    matchedBaseIndexes,
    matchedCandidateIndexes,
  };
}

function buildArrayDiff<
  BaseItem extends {
    id: string;
    status: string;
    provenance: {
      type:
        | "document_extraction"
        | "manual_amendment";
    };
  },
  CandidateItem,
>(data: {
  section: ScopeDiffSection;
  baseItems: BaseItem[];
  candidateItems: CandidateItem[];
  getIdentity: (
    item: BaseItem | CandidateItem,
  ) => string;
  getSimilarity: (
    base: BaseItem,
    candidate: CandidateItem,
  ) => number;
  isSameMeaning: (
    base: BaseItem,
    candidate: CandidateItem,
  ) => boolean;
}): Array<
  ScopeDiffEntry<BaseItem, CandidateItem>
> {
  const {
    section,
    baseItems,
    candidateItems,
    getIdentity,
    getSimilarity,
    isSameMeaning,
  } = data;

  const {
    matchedBaseIndexes,
    matchedCandidateIndexes,
  } = matchItems({
    baseItems,
    candidateItems,
    getIdentity,
    getSimilarity,
  });

  const entries: Array<
    ScopeDiffEntry<
      BaseItem,
      CandidateItem
    >
  > = [];

  // ---------------------------------------------------------------------------
  // Existing base items are emitted first so the future review UI has a
  // stable representation of the current scope.
  // ---------------------------------------------------------------------------

  for (
    let baseIndex = 0;
    baseIndex < baseItems.length;
    baseIndex += 1
  ) {
    const baseItem =
      baseItems[baseIndex];

    const candidateIndex =
      matchedBaseIndexes.get(
        baseIndex,
      );

    // Already removed items remain tombstones unless the new SOW
    // explicitly brings them back.
    if (
      baseItem.status === "removed"
    ) {
      if (
        candidateIndex ===
        undefined
      ) {
        continue;
      }

      const candidateItem =
        candidateItems[candidateIndex];

      entries.push({
        status: "CONFLICT",
        baseItem,
        candidateItem,
        baseItemId: baseItem.id,
        candidateIndex,
        matchMethod:
          getIdentity(
            baseItem,
          ) ===
          getIdentity(
            candidateItem,
          )
            ? "exact-key"
            : "fuzzy",
        matchScore:
          getSimilarity(
            baseItem,
            candidateItem,
          ),
        requiresCarryOverDecision: false,
        conflictType:
          "REMOVED_ITEM_REAPPEARED",
      });

      continue;
    }

    // Active item exists in the old scope.
    if (
      candidateIndex ===
      undefined
    ) {
      entries.push({
        status: "MISSING",
        baseItem,
        candidateItem: null,
        baseItemId: baseItem.id,
        candidateIndex: null,
        matchMethod: "none",
        matchScore: null,
        requiresCarryOverDecision:
          baseItem.provenance.type ===
          "manual_amendment",
        conflictType: null,
      });

      continue;
    }

    const candidateItem =
      candidateItems[candidateIndex];

    const identityMatch =
      normalizeComparableText(
        getIdentity(baseItem),
      ) ===
      normalizeComparableText(
        getIdentity(
          candidateItem,
        ),
      );

    entries.push({
      status: isSameMeaning(
        baseItem,
        candidateItem,
      )
        ? "UNCHANGED"
        : "MODIFIED",

      baseItem,
      candidateItem,

      baseItemId:
        baseItem.id,

      candidateIndex,

      matchMethod:
        identityMatch
          ? "exact-key"
          : "fuzzy",

      matchScore:
        getSimilarity(
          baseItem,
          candidateItem,
        ),

      requiresCarryOverDecision:
        false,

      conflictType: null,
    });
  }

  // ---------------------------------------------------------------------------
  // Candidate items without a base match are additions.
  // ---------------------------------------------------------------------------

  for (
    let candidateIndex = 0;
    candidateIndex < candidateItems.length;
    candidateIndex += 1
  ) {
    if (
      matchedCandidateIndexes.has(
        candidateIndex,
      )
    ) {
      continue;
    }

    entries.push({
      status: "ADDED",
      baseItem: null,
      candidateItem:
        candidateItems[candidateIndex],
      baseItemId: null,
      candidateIndex,
      matchMethod: "none",
      matchScore: null,
      requiresCarryOverDecision:
        false,
      conflictType: null,
    });
  }

  return entries;
}

/**
 * Timeline is a singleton, so it is diffed field-by-field rather than
 * being matched as an array item.
 */
function diffTimeline(
  baseTimeline: NormalizedScope["timeline"],
  candidateTimeline: ExtractedScope["timeline"],
): TimelineDiff {
  const baseDuration =
    normalizeComparableText(
      baseTimeline.duration,
    );

  const candidateDuration =
    normalizeComparableText(
      candidateTimeline.duration,
    );

  const baseStart =
    normalizeComparableText(
      baseTimeline.startCondition,
    );

  const candidateStart =
    normalizeComparableText(
      candidateTimeline.startCondition,
    );

  const baseDependencies =
    new Set(
      baseTimeline.dependencies
        .map(normalizeComparableText)
        .filter(Boolean),
    );

  const candidateDependencies =
    new Set(
      candidateTimeline.dependencies
        .map(normalizeComparableText)
        .filter(Boolean),
    );

  const dependenciesEqual =
    baseDependencies.size ===
      candidateDependencies.size &&
    [...baseDependencies].every(
      (dependency) =>
        candidateDependencies.has(
          dependency,
        ),
    );

  const changedFields: TimelineDiff["changedFields"] =
    [];

  if (
    baseDuration !==
    candidateDuration
  ) {
    changedFields.push(
      "duration",
    );
  }

  if (
    baseStart !==
    candidateStart
  ) {
    changedFields.push(
      "startCondition",
    );
  }

  if (!dependenciesEqual) {
    changedFields.push(
      "dependencies",
    );
  }

  const baseHasContent =
    Boolean(baseDuration) ||
    Boolean(baseStart) ||
    baseDependencies.size > 0;

  const candidateHasContent =
    Boolean(candidateDuration) ||
    Boolean(candidateStart) ||
    candidateDependencies.size >
      0;

  let status:
    | "UNCHANGED"
    | "MODIFIED"
    | "ADDED"
    | "MISSING";

  if (
    !baseHasContent &&
    !candidateHasContent
  ) {
    status = "UNCHANGED";
  } else if (
    !baseHasContent &&
    candidateHasContent
  ) {
    status = "ADDED";
  } else if (
    baseHasContent &&
    !candidateHasContent
  ) {
    status = "MISSING";
  } else if (
    changedFields.length > 0
  ) {
    status = "MODIFIED";
  } else {
    status = "UNCHANGED";
  }

  return {
    status,
    baseTimeline,
    candidateTimeline,
    changedFields,
  };
}

/**
 * Build the complete deterministic diff between:
 *
 *   approved persisted scope
 *              +
 *   newly extracted SOW candidate
 *
 * No AI call happens here.
 */
export function diffScopes(
  baseScope: NormalizedScope,
  candidateScope: ExtractedScope,
): ScopeDiff {
  const standardIdentity = (
    item:
      | BaseStandardItem
      | CandidateStandardItem,
  ) => item.title;

  const standardSimilarityForSection = (
    base: BaseStandardItem,
    candidate: CandidateStandardItem,
  ) =>
    standardSimilarity(
      base,
      candidate,
    );

  return {
    deliverables:
      buildArrayDiff({
        section: "deliverables",
        baseItems:
          baseScope.deliverables,
        candidateItems:
          candidateScope.deliverables,
        getIdentity:
          standardIdentity,
        getSimilarity:
          standardSimilarityForSection,
        isSameMeaning:
          sameStandardMeaning,
      }),

    features:
      buildArrayDiff({
        section: "features",
        baseItems:
          baseScope.features,
        candidateItems:
          candidateScope.features,
        getIdentity:
          standardIdentity,
        getSimilarity:
          standardSimilarityForSection,
        isSameMeaning:
          sameStandardMeaning,
      }),

    exclusions:
      buildArrayDiff({
        section: "exclusions",
        baseItems:
          baseScope.exclusions,
        candidateItems:
          candidateScope.exclusions,
        getIdentity:
          standardIdentity,
        getSimilarity:
          standardSimilarityForSection,
        isSameMeaning:
          sameStandardMeaning,
      }),

    clientResponsibilities:
      buildArrayDiff({
        section:
          "clientResponsibilities",
        baseItems:
          baseScope.clientResponsibilities,
        candidateItems:
          candidateScope.clientResponsibilities,
        getIdentity:
          standardIdentity,
        getSimilarity:
          standardSimilarityForSection,
        isSameMeaning:
          sameStandardMeaning,
      }),

    revisionLimits:
      buildArrayDiff({
        section:
          "revisionLimits",
        baseItems:
          baseScope.revisionLimits,
        candidateItems:
          candidateScope.revisionLimits,
        getIdentity: (
          item:
            | BaseRevisionLimit
            | CandidateRevisionLimit,
        ) => item.type,
        getSimilarity:
          (
            base,
            candidate,
          ) =>
            revisionLimitSimilarity(
              base,
              candidate,
            ),
        isSameMeaning:
          sameRevisionLimitMeaning,
      }),

    assumptions:
      buildArrayDiff({
        section: "assumptions",
        baseItems:
          baseScope.assumptions,
        candidateItems:
          candidateScope.assumptions,
        getIdentity: (
          item:
            | BaseAssumption
            | CandidateAssumption,
        ) => item.statement,
        getSimilarity:
          (
            base,
            candidate,
          ) =>
            assumptionSimilarity(
              base,
              candidate,
            ),
        isSameMeaning:
          sameAssumptionMeaning,
      }),

    timeline: diffTimeline(
      baseScope.timeline,
      candidateScope.timeline,
    ),
  };
}